matrix:
  include:
    - name: "erlang x bash static analysis & styling"
      language: erlang
      otp_release: 21.3
      install:
        - bash dev_install.sh
      script:
        - bash .run_dialyzer
        - ./.elvis rock
        - shellcheck *.sh

    - name: "erlang x python integration tests"
      language: python
      python: 3.6 # downgraded to avoid xenial
      cache:
        pip: true
        apt: true
      addons:
        apt:
          packages:
            - erlang
      install:
        - pip install dataclasses # necessary because we're in 3.6
        - pip install -r requirements.txt
        - pip install mypy
      script:
        - |
          (
            sleep 15s;
            timeout 45s pytest tests/test_integration.py
          ) & (
            cd core/;
            erlc *.erl;
            cd ..;
            timeout 60s
              erl -sname leoronic -setcookie `cat .leoronic_cookie` -pa core -s leoronic
              | grep -q "=ERROR REPORT=" && exit 1
          )

    - name: "python static analysis"
      language: python
      dist: xenial
      python: 3.7
      cache: pip
      install:
        - pip install -r requirements.txt
        - pip install mypy
      script:
        - mypy wrappers/python3

    - name: "python styling"
      language: python
      dist: xenial
      python: 3.7
      cache: pip
      install:
        - pip install -r requirements.txt
        - pip install black
      script:
        - black --check wrappers/python3

    - name: "python x docker integration tests & python tests"
      language: python
      dist: xenial
      python: 3.7
      addons:
        apt:
          sources:
            - docker-xenial
          packages:
            - docker
      cache: pip
      install:
        - pip install pytest pytest-cov codecov
        - pip install -r requirements.txt
        - docker pull dominicburkart/leoronic
      script:
        - docker run -d -v /var/run/docker.sock:/var/run/docker.sock dominicburkart/leoronic && pytest --cov=./
      after_success:
        - codecov # run other reports: https://docs.codecov.io/docs/merging-reports

#    - name: "rust linters"
#      language: rust
#      rust:
#        - stable
#        - beta
#      before_script:
#        - rustup component add clippy
#      script:
#        - cd wrappers/rust && cargo clippy -- -D warnings
#
#    - name: "rust tests"
#      language: rust
#      rust:
#        - stable
#        - beta
#      script:
#        - cd wrappers/rust && cargo test
