matrix:
  include:
    - name: "erlang & bash static analysis & styling"
      language: erlang
      otp_release: 21.3
      install:
        - bash dev_install.sh
      script:
        - bash .run_dialyzer
        - ./.elvis rock
        - shellcheck *.sh

    - name: "python static analysis & styling"
      language: python
      dist: xenial
      python: "3.7"
      cache: pip
      install:
        - pip install black mypy dill
      script:
        - black wrappers/python3
        - mypy wrappers/python3

    - name: "python tests"
      language: python
      dist: xenial
      python: "3.7"
      addons:
        apt:
          sources:
            - docker-xenial
          packages:
            - docker
      cache: pip
      install:
        - pip install pytest pytest-cov codecov dill
        - docker pull dominicburkart/leoronic
      script:
        - docker run -d -v /var/run/docker.sock:/var/run/docker.sock dominicburkart/leoronic && pytest --cov=./ wrappers/python3/leoronic.py tests/integration.py
        - codecov
#    - name: "erlang x python integration tests"
#      language: erlang
#      otp_release: 21.3
#      dist: xenial
#      python: "3.7"
#      script:
#        - (cd leoronic && erlc +native +debug *.erl) && erl -name leoronic -setcookie `cat .leoronic_cookie` -s leoronic
#        - python3 tests/integration.py
#
#    - name: "python x docker (no erlang)"
#      language: python
#      dist: xenial
#      python: "3.7"
#      addons:
#        apt:
#          sources:
#            - docker-xenial
#          packages:
#            - docker
#      script:
#        - docker pull dominicburkart/leoronic
#        - docker run dominicburkart/leoronic & python3 tests/integration.py  # todo
