matrix:
  include:
    - name: "erlang x bash static analysis & styling"
      language: erlang
      otp_release: 21.3
      install:
        - bash dev_install.sh
      script:
        - bash .run_dialyzer
        - ./.elvis rock
        - shellcheck *.sh

    - name: "erlang x python integration tests"
      language: erlang
      otp_release: 21.3
      cache: pip
      before_install:
        - pyenv install 3.7.0a1
        - pyenv global 3.7.0a1
      install:
        - pip install pytest pytest-cov codecov
        - pip install -r requirements.txt
        - cd core && erlc +debug *.erl
      script:
        - |
          (
            erl -sname leoronic -setcookie `cat .leoronic_cookie` -pa core -s leoronic
          ) & pytest tests/test_integration.py

    - name: "python static analysis & styling"
      language: python
      dist: xenial
      python: "3.7"
      cache: pip
      install:
        - pip install -r requirements.txt
        - pip install black mypy
      script:
        - black wrappers/python3
        - mypy wrappers/python3

    - name: "python tests & python x docker integration tests"
      language: python
      dist: xenial
      python: "3.7"
      addons:
        apt:
          sources:
            - docker-xenial
          packages:
            - docker
      cache: pip
      install:
        - pip install pytest pytest-cov codecov
        - pip install -r requirements.txt
        - docker pull dominicburkart/leoronic
      script:
        - docker run -d -v /var/run/docker.sock:/var/run/docker.sock dominicburkart/leoronic && pytest --cov=./
      after_success:
        - codecov
#    - name: "rust linters"
#      language: rust
#      rust:
#        - stable
#        - beta
#      before_script:
#        - rustup component add clippy
#      script:
#        - cd wrappers/rust && cargo clippy -- -D warnings
#
#    - name: "rust tests"
#      language: rust
#      rust:
#        - stable
#        - beta
#      script:
#        - cd wrappers/rust && cargo test
