#!/usr/bin/env bash
#requires at least one leoronic worker to be running.

name='leoronic_ghost'
cookie=`cat .leoronic_cookie`

cd `dirname "$0"`

if [ ! -f shared.beam ]; then
  echo 'Compiling native code: shared.'
  erlc +native shared.erl
fi

if [ ! -f comrade.beam ]; then
  echo 'Compiling native code: ghost.'
  erlc +native ghost.erl
fi

echo 'Initializing leoronic ghost.'
(erl -name $name -setcookie $cookie -run comrade -hidden -connect_all false)
sleep 2s
