#!/usr/bin/env bash

leoronic_task_fields=('int: Minimum memory (in bytes) needed for the task.' \
'int: Minimum number of cores needed for the task.' \
'int: Minimum storage (in bytes) needed for the task.' \
'str: Allow other concurrent tasks? true or false.' \
'str: Required conditions for running (split by ; ).' \
'str: Paths to necessary files (split by ; ).' \
'str: Bash commands that compose task.')

cookie=`cat ~/.leoronic_cookie`

leoronic_add_tag(){
  erl -sname add_tag -setcookie $cookie -hidden \
  -run comrade link_to_leoronic \
  -run comrade add_tag "$@"
}

leoronic_add_task(){
  erl -sname add_shunt -setcookie $cookie -hidden \
  -run comrade link_to_leoronic \
  -run comrade add_shunt "$@"
}

leoronic_add_tasks_from_file(){
  s=`cat ${1}`
  leoronic_add_tasks_from_str $s
}

leoronic_add_tasks_from_str(){
  com="erl -sname add_shunt -setcookie $cookie -hidden \
  -run comrade link_to_leoronic"
  IFS=$'\n' read -d '' -r -a tasks <<< ${1} #string passed, split by newlines.
  for t in tasks
  do
    com="$com -run comrade add_shunt $t"
  done
  eval com
}

leoronic_del_task(){
  erl -sname add_shunt -setcookie $cookie -hidden \
  -run comrade link_to_leoronic \
  -run comrade del_shunt "$@"
}

leoronic_get_queue(){
  `erl -sname get_queue -setcookie $cookie`
}

example=
leoronic_task_format(){
  printf 'below are the parameters for declaring a new task:\n\n'
  printf "%s\n" "${leoronic_task_fields[@]}"
  printf '\n\nexample task:\n'
  printf
}
