#!/usr/bin/env bash


name='leoronic'
cookie=`cat .leoronic_cookie`

cd `dirname "$0"`

if [ ! -f shared.beam ]; then
  echo 'Compiling native code: shared.'
  erlc +native shared.erl
fi

if [ ! -f comrade.beam ]; then
  echo 'Compiling native code: comrade.'
  erlc +native comrade.erl
fi

echo 'Initializing Leoronic.'
(erl +c true -name $name -setcookie $cookie -run comrade)
sleep 2s
