#!/usr/bin/env bash

./compile_and_run > erlang_output &
./pytest_integration > pytest_output &
sleep 30
tail pytest_output | grep -q "==== [0-9]* passed in [0-9]*\.[0-9]* seconds ====" && exit 0
cat pytest_output
echo "timeout in python_integration_test"
exit 1