#!/usr/bin/env bash

# start test processes
./compile_and_run > erlang_output &
./pytest_integration > pytest_output &

# check in on the test processes after a bit
sleep 30
tail pytest_output | grep -q "==== [0-9]* passed in [0-9]*\.[0-9]* seconds ====" && exit 0

# timeout reached; exit with failure
echo -e "BEGIN ERLANG OUTPUT\n\n\n"
cat erlang_output
echo -e "\n\n\nEND ERLANG OUTPUT. BEGIN PYTEST OUTPUT\n\n\n"
cat pytest_output
echo -e "\n\n\nEND PYTEST OUTPUT"
echo "timeout in python_integration_test"
exit 1
